export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const SINGLE_CHARCTER = "SINGLE_CHARACTER";
export const SET_LOADING = "SET_LOADING";